[package]
name = "chatter_web"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
rocket.workspace = true
serde.workspace = true
log.workspace = true
zeroize.workspace = true
db.workspace = true
crypto.workspace = true
chrono.workspace = true
tokio.workspace = true
